### ISSUE TITLE
Add "max" method

### ISSUE THREAD

**Issue by marcuspoehls** [superchargejs/collections#15]
The `collection.max()` method returns the max value in the collection:

**Example**

```js
await Collect([1, 20, 3, 4])
  .max()

// 20
```

**Comment by marcuspoehls** [comment]
Please notice, I'll favor a PR from @fernandadagostin (details in https://github.com/superchargejs/collections/issues/7#issuecomment-539039300)

**Comment by dragonstin** [comment]
I am working on it.

**Comment by marcuspoehls** [comment]
@fernandadagostin That's great! Please don't feel rushed. Take the time you need
