### ISSUE TITLE
Add "min" method

### ISSUE THREAD

**Issue by marcuspoehls** [superchargejs/collections#18]
The `collection.min()` method returns the min value in the collection:

**Example**

```js
await Collect([10, 2, 3, 4])
  .min()

// 2
```

**Comment by marcuspoehls** [comment]
Please notice, I’ll favor a PR from @RShalman (details in https://github.com/superchargejs/collections/pull/16#issuecomment-539290887)

**Comment by jackneer** [comment]
I'd like to work on it.

**Comment by RShalman** [comment]
> I'd like to work on it.

Already doing this :)

**Comment by jackneer** [comment]
> > I'd like to work on it.
> 
> Already doing this :)

no problem
