### ISSUE TITLE
Add "join" method

### ISSUE THREAD

**Issue by marcuspoehls** [superchargejs/collections#23]
The `collection.join(str)` method joins all items in the collection using the given `str` and returns the resulting string value:

**Example**

```js
await Collect([10, 2, 3, 4])
  .join('-')

// '10-2-3-4' 
```

**Comment by mcvladthegoat** [comment]
Hi @marcuspoehls !
I can do it :) Could you please assign it to me?

**Comment by mcvladthegoat** [comment]
@marcuspoehls i have one question. What is expected in cases of:
```javascript
await Collect([10,2,3,4]).join()
// maybe '10,2,3,4', according to standart Array.join
```
and 
```javascript
await Collect([10,2,3,4]).join('')
// maybe '10234', according to standart Array.join
```

**Comment by marcuspoehls** [comment]
@mcvladthegoat Hey Vlad, good question! Thank you for proposing the solutions and keeping the behavior of Array#join into account. Yep, please implement these cases the way you proposed them (same way as `Array#join` handles them). Thank you!

**Comment by mcvladthegoat** [comment]
@marcuspoehls thx, i'll push PR today

**Comment by marcuspoehls** [comment]
@mcvladthegoat Cool!
