### ISSUE TITLE
Add "reverse" method

### ISSUE THREAD

**Issue by marcuspoehls** [superchargejs/collections#25]
The `collection.reverse()` method reverses the collection. The first item becomes the last one, the second item becomes the second to last, and so on:

**Example**

```js
await Collect([4, 6, 8, 9])
  .reverse()
  .all()

// [9, 8, 6, 4]
```

**Comment by ilyaryabchinski** [comment]
Hi! I want to contribute!
Could you please assign it to me?

**Comment by ilyaryabchinski** [comment]
Thanks!
Waiting for review
