### ISSUE TITLE
Add "last" method

### ISSUE THREAD

**Issue by marcuspoehls** [superchargejs/collections#38]
The `colleciton.last()` method returns the last item in the collection. It does not remove the item from the collection:

**Example**

```js
const collection = Collect([ 1, 2, 3 ])

await collection.last()

// 3

await collection.all()

// [ 1, 2, 3 ]
```

It wouuld be great to let users pass an (async) testing function as a parameter to the `last` method:

```js
await Collect([
  { id: 1, name: 'marcus' },
  { id: 3, name: 'marcus' }
]).last(async ({ id }) => {
  return await User.findById(id)
})

// { id: 3, name: 'marcus', username: 'marcus' }
```

**Comment by Anilpandiya** [comment]
@marcuspoehls i can work on this

**Comment by Anilpandiya** [comment]
PR raised - [last method](https://github.com/superchargejs/collections/pull/43)
