### ISSUE TITLE
Add "intersect" method

### ISSUE THREAD

**Issue by marcuspoehls** [superchargejs/collections#4]
The `collection.intersect(array)` method removes all values from the `collection` that are not present in the given `array`.

**Example**

```js
await Collect([1, 2, 3])
  .intersect([2, 3, 4, 5])
  .all()

// [2, 3]
```

**Comment by dev-warner** [comment]
I don't mind taking this one

**Comment by dev-warner** [comment]
PR is here https://github.com/superchargejs/collections/pull/13

**Comment by marcuspoehls** [comment]
@dev-warner awesome, thank you Joe!
