### ISSUE TITLE
Collections vs lodash

### ISSUE THREAD

**Issue by venikman** [superchargejs/collections#46]
I am not a user of any functional library but I have an idea what they do. Can you @marcuspoehls  explain what the difference between this `collections` and any other library?

**Comment by marcuspoehls** [comment]
@venikman Hey Stanislau, this collections package is a wrapper around JavaScript's arrays. It doesn't support direct interactions with objects like lodash does.

This collections package exists to provide async callbacks for JavaScript's array methods. For example, you can't simply provide an async callback to JavaScript's `Array#map` and chain async `Array#filter` and `Array#recude` methods. You'll receive an array of promises from `Array#map` which you need to await before running the `Array#filter` method. Same here, you need to await the returned array of promises before running `Array#reduce`.

This collections package supports async callbacks and you can simply chain all operations and await the result.

Also, this collections package provides a handful of convenient methods additionally to JavaScripts `Array` class.

Does this description help you?

**Comment by venikman** [comment]
oh now I see. Thanks for explanation @marcuspoehls.
