### ISSUE TITLE
Add "union" method

### ISSUE THREAD

**Issue by marcuspoehls** [superchargejs/collections#5]
The `collection.union(array)` method adds all values from the `array` and removes duplicates:

**Example**

```js
await Collect([1, 2, 3])
  .union([2, 3, 4, 5])
  .all()

// [1, 2, 3, 4, 5]
```

**Comment by dev-warner** [comment]
Hey i've created a PR here, let me know if there's any issues/improvements https://github.com/superchargejs/collections/pull/11
