### ISSUE TITLE
Add "includes" method

### ISSUE THREAD

**Issue by marcuspoehls** [superchargejs/collections#81]
Add a new `.includes(value|predicate-fn)` method that determines whether the collection includes a certain `value`. The `.includes()` method allows either a dedicated value or a predicate function receiving a collection item (like `.find()`).

Returns `true` if the value is found in the collection or the predicate function returns an item from the collection. Returns false otherwise.

**Notice:** this is basically an alias for the existing `.has` method. 

**Example**

```js
const collection = Collect([ 1, 2, 3 ])

await collection.includes(2)
// true

await collection.includes((value => {
  return value > 5
})
// false
```

**Comment by bengry** [comment]
Can I work on this?

**Comment by lukas-mertens** [comment]
I am going to work on this, let's see how it goes ;)

**Comment by marcuspoehls** [comment]
@lukas-mertens Hey Lukas, that's great! Thank you!
